services:
  portfolio:
    build:
      context: .
      args:
        - NEXT_PUBLIC_TURNSTILE_SITE_KEY=${NEXT_PUBLIC_TURNSTILE_SITE_KEY}
    image: portfolio:latest
    container_name: portfolio
    restart: always
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - .env
